### ISSUE TITLE
今天打开了突然显示一串编码，内容图片都加载不出来

### ISSUE THREAD

**Issue by 36721** [gentlemansolo/JavbuslibraryRealse#12]
![Screenshot_20200424_111131_cn slh javdb](https://user-images.githubusercontent.com/64240614/80171281-84984780-861c-11ea-8e8e-5cd8701e9460.jpg)

**Comment by blinkblink0** [comment]
同问

**Comment by wunai1234** [comment]
我也是 同问

**Comment by 2284787774** [comment]
我也是

**Comment by gentlemansolo** [comment]
因为网站加入了cloudflare防护，已修复，升级到v2.7.1
