### ISSUE TITLE
更新之后，连接失败

### ISSUE THREAD

**Issue by poirotluo** [gentlemansolo/JavbuslibraryRealse#14]
Failed to connect to javdb4.com/104.26. 6.146:443

**Comment by gentlemansolo** [comment]
多试几次

**Comment by poirotluo** [comment]
不行啊，试了好几次了(✪▽✪)

**Comment by gentlemansolo** [comment]
你直接在浏览器访问javdb4.com看看

**Comment by poirotluo** [comment]
浏览器能打开

**Comment by gentlemansolo** [comment]
你截图我看看错误的地方

**Comment by poirotluo** [comment]
![TIM图片20200427170909](https://user-images.githubusercontent.com/32698827/80355316-7e1eff80-88aa-11ea-800b-4d3e2c5b3c66.jpg)

**Comment by gentlemansolo** [comment]
你换个网络试试，比如wifi

**Comment by poirotluo** [comment]
wifi，流量，甚至vpn都不行

**Comment by gentlemansolo** [comment]
你是2.7.1版本吗？，清除数据重置试试，如果你会的话尝试用ping，ping一下上面的地址看看能不能访问

**Comment by gentlemansolo** [comment]
你是不是修改过什么，比如针对这个应用加了代理，这个端口貌似不正常

**Comment by silkmother** [comment]
我5.2版本也不行
