### ISSUE TITLE
APP卡在空白页无法操作

### ISSUE THREAD

**Issue by TinyLord** [gentlemansolo/JavbuslibraryRealse#17]
APP显示纯白界面，无法操作

卡死后返回桌面的手势操作失效。左右边缘返回可以操作但没效果。下拉菜单正常操作

手机Mate9，EMUI9.1.0。2.7到3.0版本的APP均出现上述问题

**Comment by kjsolo** [comment]
操作步骤说一下，什么时候显示纯白界面，是第一次打开应用吗？

**Comment by TinyLord** [comment]
> 操作步骤说一下，什么时候显示纯白界面，是第一次打开应用吗？

是的，就是刚打开的时候

**Comment by gentlemansolo** [comment]
> > 操作步骤说一下，什么时候显示纯白界面，是第一次打开应用吗？
> 
> 是的，就是刚打开的时候

现在还会么

**Comment by TinyLord** [comment]
> > > 操作步骤说一下，什么时候显示纯白界面，是第一次打开应用吗？
> > 
> > 
> > 是的，就是刚打开的时候
> 
> 现在还会么

用了这几天发现原因了

我使用的是Clash规则模式，经常出现白屏问题，使用全局模式之后出现白屏的次数就少很多了。所以应该是APP使用的网址没在规则列表里面，APP直连网站

我在想是不是APP加载和网络请求是异步请求，但是页面在网络请求返回之后才渲染主页，如果是的话是不是改成主页占位，等网络请求返回之后再重新刷新主页好一点

**Comment by gentlemansolo** [comment]
除了第一次初始化数据会白屏，其他情况应该都是先出现占位图，然后再加载网络的
如下图：

![middle_img_05156ea4-7a8a-4f12-ba13-7e8f0ee76bbg](https://user-images.githubusercontent.com/34267096/82773707-47221680-9e75-11ea-9940-9af832b63e0c.jpg)

所以我有点奇怪你说的经常出现白屏，因为即使没有网络也是会出现以上画面。
