### ISSUE TITLE
排序和演员问题

### ISSUE THREAD

**Issue by jzysl123** [gentlemansolo/JavbuslibraryRealse#2]
类别按最新排序只是显示有磁力链接的番号 可以加个显示所有的。。

演员应该根据图书馆的数据来。
例如SGA-139图书馆显示正确 javbus和app显示错误

**Comment by gentlemansolo** [comment]
嗯，目前只显示有磁力的，下一步会进行完善

emm，演员的数据确实有问题，这个问题我研究一下

**Comment by gentlemansolo** [comment]
目前不在维护javbus1.0，所以关闭这个issues
