### ISSUE TITLE
建议增加“收藏”功能

### ISSUE THREAD

**Issue by whalien520** [gentlemansolo/JavbuslibraryRealse#4]
看到喜爱的片子或者演员不能收藏岂不遗憾？！希望购后续增加此类功能

**Comment by sf1010** [comment]
同建议增加收藏功能，可以只在本地生成json数据然后用户手动备份还原就好

**Comment by gentlemansolo** [comment]
> 同建议增加收藏功能，可以只在本地生成json数据然后用户手动备份还原就好

嗯，正在考虑

**Comment by gentlemansolo** [comment]
2.1已加入
